parameters:
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/dn
  lower: 0.0002
  upper: 0.0009
  logscale: false
  - file: fabm.yaml
  key: instances/selmaprotbas/parameters/dn_sed
  lower: 0.0002
  upper: 0.001
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/q10_rec
  lower: 0.1
  upper: 0.13
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/q10_recs
  lower: 0.1
  upper: 0.13
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/sedrate
  lower: 0.5
  upper: 2.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/br0
  lower: 0.01
  upper: 0.08
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/fds
  lower: 0.7
  upper: 0.99
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/wdz
  lower: -2.0
  upper: 0.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/wpo4
  lower: -2.0
  upper: 0.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/mbnnrate
  lower: 0.02
  upper: 0.2
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/mbsrate
  lower: 0.02
  upper: 0.2
  logscale: false
  key: instances/selmaprotbas/parameters/den_frac_denanmx_sed
  lower: 0.5
  upper: 1.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/tau_crit
  lower: 0.01
  upper: 0.1
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/po4ret
  lower: 0.0
  upper: 1.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pburialrate
  lower: 0.05
  upper: 0.2
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/fl_burialrate
  lower: 0.001
  upper: 0.009
  logscale: true
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pliberationrate
  lower: 0.001
  upper: 0.01
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pvel
  lower: 2.0
  upper: 6.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/kc
  lower: 0.0001
  upper: 0.0008
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/nitrif_rate
  lower: 0.005
  upper: 0.03
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/rfr
  lower: 0.0095
  upper: 0.015
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/rfn
  lower: 0.15
  upper: 0.18
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/alpha_n
  lower: 0.01
  upper: 0.04
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/alpha_p
  lower: 0.001
  upper: 0.005
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/r0
  lower: 1.3
  upper: 4.0
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/deltao
  lower: 0.01
  upper: 0.05
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/nb
  lower: 0.001
  upper: 0.05
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/kc
  lower: 0.0008
  upper: 0.0014
  logscale: false
  key: instances/CyanoMC/parameters/temp_opt
  lower: 14
  upper: 18
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/temp_min
  lower: 9
  upper: 13
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/alpha_light
  lower: 0.05
  upper: 0.7
  logscale: false
- file: fabm.yaml
  key: instances/CyanoMC/parameters/imin
  lower: 0
  upper: 25
  logscale: false

- file: fabm.yaml
  key: instances/NfixCyano/parameters/rfr
  lower: 0.0085
  upper: 0.0095
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/rfn
  lower: 0.15
  upper: 0.2
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/alpha_p
  lower: 0.0001
  upper: 0.0006
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/r0
  lower: 1.3
  upper: 3.0
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/deltao
  lower: 0.03
  upper: 0.1
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/nb
  lower: 0.001
  upper: 0.01
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/kc
  lower: 0.0008
  upper: 0.0016
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/temp_opt
  lower: 26
  upper: 32
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/temp_min
  lower: 15
  upper: 20
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/alpha_light
  lower: 0.05
  upper: 0.5
  logscale: false
- file: fabm.yaml
  key: instances/NfixCyano/parameters/imin
  lower: 0
  upper: 25
  logscale: false

- file: fabm.yaml
  key: instances/Green/parameters/rfr
  lower: 0.005
  upper: 0.0094
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/rfn
  lower: 0.1
  upper: 0.16
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/alpha_n
  lower: 0.0005
  upper: 0.002
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/alpha_p
  lower: 0.00008
  upper: 0.0005
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/r0
  lower: 1.5
  upper: 8.5
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/deltao
  lower: 0.001
  upper: 0.01
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/nb
  lower: 0.01
  upper: 0.1
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/kc
  lower: 0.0008
  upper: 0.0016
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/tll
  lower: 8
  upper: 15
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/alpha_light
  lower: 0.01
  upper: 0.5
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/imin
  lower: 0
  upper: 25
  logscale: false

- file: fabm.yaml
  key: instances/Dino/parameters/rfr
  lower: 0.007
  upper: 0.015
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/rfn
  lower: 0.13
  upper: 0.16
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/alpha_n
  lower: 0.03
  upper: 0.08
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/alpha_p
  lower: 0.002
  upper: 0.007
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/r0
  lower: 1.0
  upper: 3.5
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/deltao
  lower: 0.05
  upper: 0.11
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/nb
  lower: 0.001
  upper: 0.012
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/kc
  lower: 0.0008
  upper: 0.0016
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/temp_opt
  lower: 18
  upper: 25
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/temp_min
  lower: 10
  upper: 14
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/alpha_light
  lower: 0.1
  upper: 0.5
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/imin
  lower: 0
  upper: 25
  logscale: false

