parameters:
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/dn
  lower: 0.0015
  upper: 0.0045
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/dn_sed
  lower: 0.001
  upper: 0.003
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/q10_rec
  lower: 0.075
  upper: 0.225
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/q10_recs
  lower: 0.0875
  upper: 0.2625
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/sedrate
  lower: 1.125
  upper: 3.375
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/br0
  lower: 0.015
  upper: 0.045
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/fds
  lower: 0.35
  upper: 1.0
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pvel
  lower: 2.5
  upper: 7.5
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/wdz
  lower: -6.75
  upper: -2.25
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/mbsrate
  lower: 0.05
  upper: 0.15
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pburialrate
  lower: 0.0035
  upper: 0.105
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/fl_burialrate
  lower: 0.0005
  upper: 0.0015
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/wpo4
  lower: -1.5
  upper: -0.5
  logscale: false
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/sedratepo4
  lower: 0.25
  upper: 0.75
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/eroratepo4
  lower: 3.0
  upper: 9.0
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/po4ret
  lower: 0.09
  upper: 0.27
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/pliberationrate
  lower: 0.05
  upper: 0.15
- file: fabm.yaml
  key: instances/selmaprotbas/parameters/ipo4th
  lower: 50.0
  upper: 150.0

- file: fabm.yaml
  key: instances/Dino/parameters/r0
  lower: 0.65
  upper: 1.95
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/nb
  lower: 0.005
  upper: 0.015
  logscale: false 
- file: fabm.yaml
  key: instances/Dino/parameters/deltao
  lower: 0.01
  upper: 0.03
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/kc
  lower: 0.1585
  upper: 0.4755
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/Yc
  lower: 3.125
  upper: 9.375
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/temp_opt
  lower: 10.0
  upper: 30.0
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/alpha_light
  lower: 0.2
  upper: 0.4
  logscale: false
- file: fabm.yaml
  key: instances/Dino/parameters/imin
  lower: 0.0
  upper: 50.0
  logscale: false
  
- file: fabm.yaml
  key: instances/Green/parameters/wz
  lower: -0.1
  upper: 0.3
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/deltao
  lower: 0.0025
  upper: 0.0075
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/nb
  lower: 0.0005
  upper: 0.0015
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/alpha_light
  lower: 0.3
  upper: 0.9
  logscale: false
- file: fabm.yaml
  key: instances/Green/parameters/imin
  lower: 0.0
  upper: 50.0
  logscale: false  